version: "0.0"

services:
  uhppoted-mqtt:
    container_name: uhppoted-mqtt
    restart: unless-stopped
    image: ghcr.io/uhppoted/mqttd:latest
    volumes:
      - uhppoted:/usr/local/etc/uhppoted
    network_mode: "bridge"
    ports:
      - "60001:60001/udp"

volumes:
  uhppoted:
    name: uhppoted
